In [2]:
import numpy as np

# 1차원 배열 만들기

In [3]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

# 벡터화 연산

- 배열 객체는 배열의 각 원소에 대한 반복 연산을 하나로 처리하는 벡터화 연산(vectorized operation) 지원

In [5]:
data = [0,1,2,3,4,5,6,7,8,9]

In [6]:
ans = []
for i in data:
    ans.append(2*i)
ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

- 벡터화 연산을 사용하면 for 반복문 없이 한번의 연산으로 가능

In [9]:
x = np.array(data)

In [10]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

- 일반적인 리스트 객체에 정수를 곱하면 객체의 크기가 정수배 만큼 증가

In [12]:
lst = [0,1,2,3,4,5,6,7,8,9]
print(2*lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


- 벡터화 연산

In [13]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [14]:
2 * a + b

array([12, 24, 36])

In [15]:
a == 2

array([False,  True, False])

In [16]:
(a == 2) & (b > 10)

array([False,  True, False])

# 2차원 배열 만들기

- ndarray : N-dimensional Array
- 1차원 배열 외에 2,3차원 등 다차원 배열 자료 구조 지원
- 2차원 배열은 행렬(matrix) 라고 하는데, 가로줄을 행(row), 세로줄을 열(column)
- 리스트의 리스트(list of list)를 이용하면 2차원 배열 생성할 수 있음
- 안쪽 리스트의 길이는 행렬의 열의 수 (가로) / 바깥쪽 리스트는 행의 수(세로) 크기

In [18]:
c = np.array([[0,1,2],[3,4,5]]) #  2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
# 행의 개수
print(len(c))
# 열의 개수
print(len(c[0]))

2
3


* 연습 문제 1 : 넘파이를 사용하여 행렬 만들기 

In [26]:
ex1 = np.array([[10,20,30,40],[50,60,70,80]])
ex1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# 3차원 배열 만들기 

- 리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성 가능
- 크기를 나타낼 때 가장 바깥쪽 리스트 길이부터 안쪽 리스트 길이의 순서로 표시

In [28]:
# 2 x 3 x 4 array
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
              [[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

# 배열의 차원과 크기 알아내기

- 배열의 크기 및 차원을 구하는 방법은 배열의 ndim / shape 속성 사용
- ndim : 배열의 차원
- shape : 배열의 크기 

In [31]:
# a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [33]:
# c = np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [35]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


# 배열의 인덱싱

- 일차원 배열의 인덱싱은 리스트의 인덱싱과 같음

In [37]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4


- 다차원 배열일 때는 콤마(,)를 사용하여 접근
- 콤마(,)로 구분된 차원을 축(axis) 라고 함.(x축, y축)

In [38]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
print(a[0,0])
print(a[1,0])
print(a[-1,-1])

0
3
5


# 배열 슬라이싱

- 배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면, 일반 파이썬 슬라이싱과 콤마 같이 사용

In [41]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
# 첫번째 행 전체
a[0,:]
# 두번째 열 전체
a[:,1]
# 두번째 행의 두번째 열부터 끝 열까지
a[1,1:]
# 0,1,4,5 만 슬라이싱
a[:2,:2]

array([[0, 1],
       [4, 5]])

- 연습문제 2 : 다음 행렬이 있을 때,
 m = np.array([[0,1,2,3,4],[5,6,7,8,9], [10,11,12,13,14]])
 1. 이 행렬에서 값 7 인덱싱
 2. 이 행렬에서 값 14 인덱싱
 3. 이 행렬에서 배열 [6,7] 슬라이싱
 4. 이 행렬에서 배열 [7,12] 슬라이싱
 5. 이 행렬에서 배열 [[3,4], [8,9]] 슬라이싱

In [49]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
print(m[1,2])
print(m[2,-1])
print(m[1,1:3])
print(m[1:3,2])
print(m[:2,3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


# 배열 인덱싱

- 넘파이 배열 객체의 다른 강력한 기능은 팬시 인덱싱(fancy indexing) 이라는 배열 인덱싱 방법
- 데이터베이스의 질의(Query)기능을 수행
- 배열 인덱싱에서는 대괄호 ([]) 안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또 다른 ndarray)배열을 받을 수 있음
- 이러한 배열 인덱싱 방식은 불리언(Boolean) 배열과 정수 배열 방식이 있음
- 불리안 배열 인덱싱 : 인덱스 배열 원소가 True, False / 배열의 크기가 ndarray 크기와 같아야 함
- 예를 들어 1차원 ndarray에서 짝수인 원소만 골라내려면 짝수 원소에 대해 대응하는 인덱스가 True이고, 홀수 원소에 대응하는 인덱스 값이 False인 인덱스 배열을 넣음

In [54]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [55]:
# 조건문 연산을 사용시 아래와 같이 간단하게 사용 가능
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [56]:
print(a%2 == 0)
print(a[a%2 ==0])

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


- 정수 배열 인덱싱에서는 인덱스 배열의 원소 각각이 원래 ndarray 객체 원소 하나를 가르키는 인덱스 정수여야 함
- 1차원 배열에서 홀수번째 원소만 골라내는 것은 다음과 같음

In [57]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

- 아래와 같은 경우 배열 인덱스의 크기가 원래 배열 크기와 달라도 상관 없음
- 같은 원소를 반복해서 가르키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 함

In [58]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

 - fancy indexing (배열 인덱싱)은 다차원 배열의 각 차원에 대해서도 가능

In [59]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [64]:
a[:, [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [63]:
a[[2,0,1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

- 연습문제 3 : 다음 행렬과 같은 배열이 있을 때
 x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
 1. 이 배열에서 3의 배수 찾기
 2. 이 배열에서 4로 나누면 1이 남는 수 찾기
 3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남은 수 찾기

In [65]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,19,20])

In [66]:
print(x[x%3 == 0])
print(x[x%4 == 1])
print(x[(x%3 ==0) & (x%4 ==1)])

[ 3  6  9 12 15]
[ 1  5  9 13 17]
[9]


# 배열의 생성과 변형

### 넘파이의 자료형

- 넘파이의 배열 ndarray 클래스는 원소가 모두 같은 자료형이여야 함
- array 명령으로 배열을 만들 때, dtype 사용
- 쓰지 않으면 알아서 유추함
- 만들어진 배열의 자료형을 알아내려면 dtype 속성

In [67]:
x = np.array([1,2,3])
x.dtype

dtype('int64')

In [68]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [69]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [70]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [71]:
x[0] + x[1]

3.0

In [72]:
x = np.array([1,2,3], dtype='U')
x.dtype

dtype('<U1')

In [73]:
x[0] + x[1]

'12'

# Inf와 NaN 

- 넘파이에서 무한대를 표현하기 위한 np.inf(Infinity)와
- 정의할 수 없는 숫자를 나타내는 np.NaN(not a number)
- 다음과 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf가 나옴
- 0을 0으로 나누려고 하면 np.nan이 나옴

In [77]:
np.array([0,-1,-1,0])/np.array([1,0,0,0])

/Users/Mac/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/Mac/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0., -inf, -inf,  nan])

In [78]:
print(np.log(0))
print(np.exp(-np.inf))

-inf
0.0


/Users/Mac/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


# 배열 생성

In [87]:
a= np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [88]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
c = np.zeros((5,2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [90]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [91]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [92]:
e = np.ones((2,3,4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

- 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 ㅅㅇ성하고 싶으면
- ones_like, zeros_like 명령

In [95]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [96]:
g = np.empty((4,3))
g

array([[-0.00000000e+000, -0.00000000e+000,  6.79038653e-313],
       [ 6.79038653e-313,  2.14321575e-312,  6.79038654e-313],
       [ 2.01589600e-312,  2.22809558e-312,  2.01589600e-312],
       [ 8.48798317e-313,  1.23075756e-312,  9.02415250e-309]])

- arange 명령은 Numpy 버전의 range 명령
- 특정한 규칙에 따라 증가하는 수열을 만듦

In [98]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.arange(3, 21, 2) # 시작, 끝(포함x), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

- linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 수만큼 분할함 

In [101]:
np.linspace(0, 100, 5) #시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [102]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

# 전치연산

- 2차원 배열 전치(transpose) 연산 -> 행과 열을 바꾸는 작업
- 메서드가 아닌 속성이라는 점  

In [105]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# 배열의 크기 변형

- 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 명령이나 메서드 사용
- 12개의 원소를 가진 1차원 행렬은 3x4 형태의 2차원 행렬로 만들 수 있음

In [110]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [111]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

- 다차원 배열을 1차원으로 만들기 위해서는 flatten, ravel 메서드

In [115]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 배열 사용에서 길이가 5인 1차원 배열과 행과 열 갯수가(5,1)인 
2차원 배열 또는 행, 열 개수가 (1,5)인 2차원 배열은 데이터 같아도 다른 객체임

In [117]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [118]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [119]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [120]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# 배열 연결

- hstack, vstack, dstack, stack, r_, c_, tile

In [121]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [124]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [125]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [126]:
b1 = np.ones((2,3))
print(b1)
b2 = np.zeros((3,3))
print(b2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [127]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
c1 = np.ones((3,4))
print(c1)
c2 = np.zeros((3,4))
print(c2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [131]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [132]:
(np.dstack([c1,c2])).shape

(3, 4, 2)

In [133]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [135]:
c.shape

(2, 3, 4)

In [136]:
c = np.stack([c1,c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [137]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [138]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [140]:
a= np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [141]:
np.tile(a, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

- 연습문제 3.2.1 배열 만들기

In [220]:
ex = np.array([0,0,0,1,1])
ex2 = np.arange(1,16).reshape(3,5)

In [222]:
np.tile(ex,(3,1))
np.vstack([np.tile(ex,(3,1)),ex2*10])
np.tile(np.vstack([np.tile(ex,(3,1)),ex2*10]),(2,1))

array([[  0,   0,   0,   1,   1],
       [  0,   0,   0,   1,   1],
       [  0,   0,   0,   1,   1],
       [ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [  0,   0,   0,   1,   1],
       [  0,   0,   0,   1,   1],
       [  0,   0,   0,   1,   1],
       [ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

# 2차원 그리드 포인트 생성

- 그리드 포인트를 만드는 과정을 도와주는 meshgrid 명령

In [186]:
x = np.arange(3)
x

array([0, 1, 2])

In [187]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [188]:
X,y = np.meshgrid(x,y)
X,y

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

# 배열의 연산

### 벡터화 연산

In [192]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [196]:
%%time

z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: user 9.59 ms, sys: 1.51 ms, total: 11.1 ms
Wall time: 10.7 ms


In [197]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [198]:
%%time
z = x+y

CPU times: user 130 µs, sys: 109 µs, total: 239 µs
Wall time: 170 µs


In [199]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

- 사칙연산뿐 아니라 비교 연산과 같은 논리연산도 벡터화 연산 가능

In [201]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

print(a == b)
print(a >= b)

[False  True False  True]
[False  True  True  True]


In [202]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [203]:
np.all(a==b)

False

In [204]:
np.all(a==c)

True

In [205]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [206]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [207]:
10 ** a

array([    1,    10,   100,  1000, 10000])

In [208]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

# 스칼라와 벡터/행렬의 곱셈

In [209]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [211]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [212]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

# 브로드캐스팅

- 서로 다른 크기의 벡터/행렬의 사칙연산 지원 
- 크기가 작은 배열을 자동으로 반복 확장

In [223]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [224]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [225]:
x + y

array([1, 2, 3, 4, 5])

In [226]:
x + 1

array([1, 2, 3, 4, 5])

In [227]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [228]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [229]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [230]:
y = np.arange(3)
y

array([0, 1, 2])

In [231]:
x+ y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

# 차원 축소 연산

 -  최대/최소 : min, max, argmin, argmax
 -  통계 : sum, mean, median, std, var
 - 불리언 : all, any

In [232]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [233]:
np.sum(x)

10

In [234]:
x.sum()

10

In [235]:
x = np.array([1,3,2])

In [237]:
print(x.min())
print(x.max())
print(x.argmin()) # 최소값의 위치
print(x.argmax()) # 최대값의 위치

1
3
0
1


In [239]:
x = np.array([1,2,3,1])

In [241]:
print(x.mean())
print(np.median(x))
print(np.all([True,True,False]))
print(np.any([True, True, False]))

1.75
1.5
False
True


In [242]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [244]:
print(np.any(a!=0))
print(np.all(a==a))

False
True


In [245]:
a= np.array([1,2,3,2])
b= np.array([2,2,3,2])
c= np.array([6,4,4,5])

In [247]:
((a<=b) & (b <=c)).all()

True

In [248]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [249]:
x.sum()

6

In [251]:
print(x.sum(axis=0)) #열합계
print(x.sum(axis=1)) #행합계

[3 3]
[2 4]


- 연습문제 3.3.1 : 실수로 이루어진 5x6 데이터 행렬 만들고 이 데이터에 대한 다음의 값 구하기
1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최소값

In [276]:
ex3_3 = np.ones((5,6),dtype="f")

In [278]:
print(ex3_3.max())
print(ex3_3.sum())
print(ex3_3.max(axis=1))
print(ex3_3.mean(axis=0))
print(ex3_3.min(axis=0))

1.0
30.0
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]


# 정렬

In [279]:
a = np.array([[4,3,5,7],[1,12,11,9],[2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [281]:
np.sort(a) # axis = 1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [282]:
np.sort(a, axis= 0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [285]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

- 자료를 정렬하는 것이 아니라 순서만 알고 싶으면 argsort 명령 사용

In [287]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [288]:
a[j]

array([12, 25, 38, 42])

In [289]:
np.sort(a)

array([12, 25, 38, 42])

- 연습문제 3.3.2 : 다음 배열은 첫번째행(row)에 학번, 두번째 행에 영어성적, 
세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬

In [303]:
e = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
e

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [308]:
e_args = e[1].argsort()
e_args

array([0, 3, 1, 2])

In [309]:
e[:,e_args]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

# 기술 통계

In [324]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
             2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])

# 데이터의 개수

In [311]:
len(x) # 개수

26

# 표본 평균

In [316]:
np.mean(x)

4.8076923076923075

In [318]:
x.sum()/len(x)

4.8076923076923075

# 표준 분산

In [319]:
np.var(x)

115.23224852071006

In [325]:
x_bar = x.sum()/len(x)

In [329]:
np.sum((x - x_bar) ** 2)/len(x)

115.23224852071006

In [332]:
np.sum((x-x_bar) ** 2)/(len(x)-1) #비편향 분산

119.84153846153846

# 난수 발생과 카운팅

- 난수(random number)

In [334]:
np.random.seed(0)

In [335]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [336]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [337]:
np.random.seed(0)

In [338]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [339]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [340]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

# 데이터의 순서 바꾸기

In [341]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [343]:
np.random.shuffle(x)
x

array([5, 7, 6, 1, 9, 3, 0, 2, 8, 4])

# 데이터 샘플링

- 이미 있는 데이터 집합에서 일부를 무작위로 선택함 : 표본선택 혹은 샘플링(sampling)
- numpy.random.choice(a, size=None, replace=True, p=None)

In [345]:
np.random.choice(5,5, replace=False) #shuffle 명령과 같음

array([3, 2, 1, 4, 0])

In [347]:
np.random.choice(5,3, replace=False) # 3개만 선택

array([4, 2, 3])

In [348]:
np.random.choice(5,10) # 반복해서 10개 선택

array([1, 1, 3, 3, 2, 3, 0, 3, 4, 1])

In [351]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) #선택 확률을 다르게 해서 10개 선택

array([3, 3, 0, 3, 0, 3, 3, 2, 3, 3])

# 난수 생성

- rand 함수는 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성
- randn 함수는 기대값이 0이고 표준편차가 1인 표준 정규 분포를 따르는 난수 생성
- randint 함수는 numpy.random.randint(low, high=None, size=None)

In [352]:
np.random.rand(10)

array([0.88047589, 0.91823547, 0.21682214, 0.56518887, 0.86510256,
       0.50896896, 0.91672295, 0.92115761, 0.08311249, 0.27771856])

In [353]:
np.random.rand(3,5)

array([[0.0093567 , 0.84234208, 0.64717414, 0.84138612, 0.26473016],
       [0.39782075, 0.55282148, 0.16494046, 0.36980809, 0.14644176],
       [0.56961841, 0.70373728, 0.28847644, 0.43328806, 0.75610669]])

In [354]:
np.random.randn(10)

array([ 0.8647491 , -0.22686923,  0.81116027,  0.28779461, -0.53846816,
        1.9084621 , -0.475776  ,  1.44073112, -1.14907568,  0.80571455])

In [355]:
np.random.randn(3,5)

array([[ 1.75610703,  0.97297991, -1.55111911,  0.19114348,  1.60477607],
       [-1.42002593, -2.44378268, -2.05633855, -0.99225755,  1.01128532],
       [ 1.40044008, -0.65499168, -0.25579069, -0.71438561, -0.50083877]])

In [356]:
np.random.randint(10, size=10)

array([8, 8, 3, 2, 3, 6, 3, 6, 5, 7])

In [357]:
np.random.randint(10, 20, size=10)

array([10, 18, 14, 16, 15, 18, 12, 13, 19, 17])

In [358]:
np.random.randint(10,20, size=(3,5))

array([[15, 13, 14, 15, 13],
       [13, 17, 19, 19, 19],
       [17, 13, 12, 13, 19]])

- 연습문제 3.5.1 
 1. 동전을 10번 던져 앞면(숫자1)과 뒷면(숫자0)이 나오는 가상실험을 파이썬으로 작성
 2. 주사위를 100번 던져서 나오는 숫자의 평균 

In [365]:
np.random.rand(100).mean()

0.5025177022033951

- 연습 3.5.2
 1. 가격이 10,000인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%, 표준편차가 1%를 따른다고 함. 250일 동안의 주가를 무작위로 생성

In [370]:
np.random.randint(10000, size=250)

array([7339, 2522, 9231, 8004, 1226, 6229,  106, 7659, 4352, 9809, 3258,
       5339, 5046, 8623, 8982, 3396, 3962,  830, 3876, 8913, 8390, 8454,
       3504, 7708, 4173, 2441,  469, 7160, 1188, 8476, 5620,  970, 9730,
       2469, 7111, 7255, 1758, 4049, 9731,  111, 6992, 1779, 4690, 4914,
       1981, 2538, 1827, 8501, 3441, 5479, 5674, 6684, 8319, 8363, 9299,
       4158, 6793, 1243, 4835, 2912, 6175, 8086, 3454, 5945, 7189, 3901,
       3881, 4971, 7831, 7421, 2792, 5940,  279, 9338, 3912, 3309,  815,
       9871, 6081, 2654,  810, 7934,  512, 2950, 4829, 3139, 4383, 2845,
       6160, 4093, 9478, 4329, 4363, 3409, 4989, 9515, 6467,  511, 2679,
       4366,  270,  447, 4469,   43, 7526, 5012, 2583, 5410, 3360, 2881,
       2837, 2628, 7981, 1000, 4888, 4020, 3720, 5345, 8442, 5898, 2622,
       1565,  139, 8519, 3642, 8149, 6471, 8857,  492,  822, 5238,  339,
       1401,  490, 7299,  884, 7124, 4081,  851, 2297, 2597, 6588,  876,
       9735, 3004, 7162, 4450, 1512, 7335, 7713, 80

# 정수 데이터 카운팅

- 이렇게 발생시킨 난수가 실수면 히스토그램 등을 사용하여 분석함
- 난수가 정수값이면 unique , bincount 로 데이터 값 분석
- unique 함수는 데이터에서 중복된 값을 제거하여 중복되지 않은 값 리스트 출력
- return_count 인수를 True로 설정하면 각 값을 가진 데이터 갯수도 출력

In [371]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [372]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [373]:
print(index)
print(count)

['a' 'b' 'c']
[2 2 1]


 - unique 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로
 데이터 값이 나올 수 있지만 데이터가 하나도 없는 경우에는 정보를 주지 않음
 - 예를 들어 주사위를 10번 던졌을 때, 6이 나오지 않으면 이 값을 0으로 세지 않음
 - 그래서 주사위와 같이 특정 범위 안의 수인 경우에는 bincount 함수에 minlength 인수 사용
 - bincount 함수는 0부터 minlength-1까지의 숫자에 대해 각각 카운트 함

In [374]:
np.bincount([1,1,2,2,2,3], minlength=6)

array([0, 2, 3, 1, 0, 0])