In [20]:
import pandas as pd
import numpy as np

In [2]:
!pip install mglearn

     |████████████████████████████████| 542kB 11.6MB/s 
  Created wheel for mglearn: filename=mglearn-0.1.9-py2.py3-none-any.whl size=582638 sha256=7e73f1381cda9ae139c94fe94783bea087d2267340e17e87931d5f2f806a3c21
  Stored in directory: /root/.cache/pip/wheels/eb/a6/ea/a6a3716233fa62fc561259b5cb1e28f79e9ff3592c0adac5f0
Successfully built mglearn


In [3]:
# example (wave dataset) k=3

In [4]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=40)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [7]:
from sklearn.neighbors import KNeighborsRegressor
reg = KNeighborsRegressor(n_neighbors=3)
reg.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                    weights='uniform')

In [8]:
y_test_hat = reg.predict(X_test)
print(y_test)
print(y_test_hat)

[ 0.37299129  0.21778193  0.96695428 -1.38773632 -1.05979555 -0.90496988
  0.43655826  0.7789638  -0.54114599 -0.95652133]
[-0.05396539  0.35686046  1.13671923 -1.89415682 -1.13881398 -1.63113382
  0.35686046  0.91241374 -0.44680446 -1.13881398]


In [10]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("MAE : ", mean_absolute_error(y_test, y_test_hat))
print("MSE : ", mean_squared_error(y_test, y_test_hat))
print("R_square :" , r2_score(y_test, y_test_hat))

MAE :  0.2537184941556285
MSE :  0.1086766237285082
R_square : 0.8344172446249605


In [11]:
# Data scaling
# example (forge dataset) with StandardScaler

In [13]:
import mglearn
X, y = mglearn.datasets.make_forge()

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function make_blobs is deprecated; Please import make_blobs directly from scikit-learn
  warnings.warn(msg, category=FutureWarning)


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train_scaled, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [18]:
from sklearn.metrics import accuracy_score
y_train_hat = clf.predict(X_train_scaled)
print("train accuarcy : ",accuracy_score(y_train, y_train_hat))
y_test_hat = clf.predict(X_test_scaled)
print("test accuarcy : ",accuracy_score(y_test, y_test_hat))

train accuarcy :  0.9473684210526315
test accuarcy :  0.8571428571428571


In [25]:
print(y_train)
print(y_test)
print(X_train)
print(X_test)
print(y_train_hat)
print(y_test_hat)

[0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 1 0 1 0]
[1 0 1 0 1 1 0]
[[ 8.92229526 -0.63993225]
 [ 8.7337095   2.49162431]
 [ 9.32298256  5.09840649]
 [ 7.99815287  4.8525051 ]
 [11.0329545  -0.16816717]
 [ 9.17748385  5.09283177]
 [11.563957    1.3389402 ]
 [ 9.15072323  5.49832246]
 [ 8.34810316  5.13415623]
 [11.93027136  4.64866327]
 [ 8.1062269   4.28695977]
 [ 8.67494727  4.47573059]
 [ 9.67284681 -0.20283165]
 [ 9.50169345  1.93824624]
 [ 8.69289001  1.54322016]
 [ 9.96346605  4.59676542]
 [ 9.50048972 -0.26430318]
 [ 9.25694192  5.13284858]
 [ 8.68937095  1.48709629]]
[[11.54155807  5.21116083]
 [10.06393839  0.99078055]
 [ 9.49123469  4.33224792]
 [ 8.18378052  1.29564214]
 [ 8.30988863  4.80623966]
 [10.24028948  2.45544401]
 [ 8.34468785  1.63824349]]
[0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 1 0 1 0]
[1 0 1 0 1 0 0]


In [47]:
# example MinMaxScaler

In [38]:
import mglearn
X, y = mglearn.datasets.make_forge()

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function make_blobs is deprecated; Please import make_blobs directly from scikit-learn
  warnings.warn(msg, category=FutureWarning)


In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [41]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [43]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train_scaled, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [46]:
from sklearn.metrics import accuracy_score
y_train_hat = clf.predict(X_train_scaled)
print('train accuracy :', accuracy_score(y_train, y_train_hat))
y_test_hat = clf.predict(X_test_scaled)
print('test accuarcy :', accuracy_score(y_test, y_test_hat))

train accuracy : 0.9473684210526315
test accuarcy : 0.8571428571428571
