# (6)  3강-1. Numpy 배열 - Part 1

### 1. Numpy 라이브러리 import

In [1]:
import numpy as np

### 2. Numpy 배열 생성 방법

#### 2-1. 리스트 활용

In [2]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
type(mylist)

list

In [7]:
arr = np.array(mylist)

In [8]:
arr

array([1, 2, 3])

#### 2-2. 중첩 리스트를 실제로는 행렬이라 불리는 numpy 배열로 변환

In [9]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
mymatrix = np.array(mylist)

In [13]:
mymatrix.shape

(3, 3)

#### 2-3. 기타 : 범위, 0과 1의 배열을 생성법, 선형 간격 배열 생성법, 난수 배열 생성법

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

- 0 뒤에 붙은 소수점은 부동 소수점 의미

In [21]:
np.zeros((4,10)) # 4행 10열 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,5)) # 5행 5열

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- numpy를 통해 배열에서 모든 단일 숫자로 연산할 수 있음

In [24]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [26]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [27]:
# 일반적인 파이썬 리스트

[1,1,1,1] * 100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [28]:
[1,1,1,1] + 10

TypeError: can only concatenate list (not "int") to list

-> 데이터 타입이 다르기 때문 그러나, Numpy는 가능

In [29]:
# 특정 간격에 따라 일정하게 생성된 숫자가 반환되는 선형 간격 배열 생성

np.linspace(0,10,3)

array([ 0.,  5., 10.])

-> 0과 10 사이의 일정한 간격으로 배치된 3개의 숫자가 나타나게 됨

In [30]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

-> 20을 입력하면 0과 10 사이에 일정한 간격으로 배치된 20개의 숫자가 나타나게 됨
-> 0 에서 시작해서 10을 포함함

In [31]:
len(np.linspace(0,10,20))

20

- np.arange(start, stop, step_size) 정수
- np.linspace(start, stop, 반환할 숫자) 

In [32]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

- 단위 행렬 생성 np.eye()

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# (7)  3강-2. Numpy 배열 - Part 2

#### 난수 생성 + 시드를 통한 난수 생성

In [37]:
#1에 대한 균등 분포에서 임의의 샘플 제공 

np.random.rand(1)

array([0.587478])

In [35]:
np.random.rand(4)

array([0.63052797, 0.40509738, 0.06393213, 0.78808151])

In [36]:
np.random.rand(5,5)  # 5x5 난수 행렬

array([[0.91405865, 0.3128029 , 0.03836949, 0.54347181, 0.58135816],
       [0.07236187, 0.57389909, 0.08167291, 0.7568053 , 0.75765782],
       [0.20030151, 0.8356949 , 0.36361325, 0.79463727, 0.52657504],
       [0.43996423, 0.65023066, 0.32224343, 0.21894987, 0.75622905],
       [0.46472596, 0.91853788, 0.15272716, 0.92777499, 0.18895928]])

In [39]:
# 표준 정규 분포에서 하나 이상의 샘플 반환 ( 평균 0, 표준편차 1)

np.random.randn(1)

array([0.15140457])

In [40]:
np.random.randn(10)

array([-0.24726808, -0.58825104,  1.9440753 , -2.39974353, -1.63777086,
        0.61927264, -0.85598379,  0.5560945 , -1.4338594 , -0.32146931])

`np.random.normal (shift+tab 으로 scaling 조정 가능)`

In [41]:
# np.random.randit : 최솟값을 포함하고 최댓값을 제외한 범위에서 임의의 정수를 반환

np.random.randint(1,100) # 1과 100 사이의 난수 생성

13

In [42]:
np.random.randint(1,100,10) # 1과 100사이의 10개 난수 생성

array([99, 24, 85, 51, 71, 62, 70, 10, 89, 28])

In [43]:
# 시드를 설정하면 

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [46]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [47]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

#### 배열의 속성과 메소드

In [48]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
ranarr = np.random.randint(0,50,10)
ranarr

array([10, 21, 27, 28, 48,  4,  1, 42, 41, 20])

In [50]:
# 형태 변경

arr.shape

(25,)

In [51]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

-> 5행 3열에는 15개의 요소만 들어가기 때문에 불가능함

#### 최대값,최소값

In [54]:
ranarr

array([10, 21, 27, 28, 48,  4,  1, 42, 41, 20])

In [55]:
ranarr.max()

48

In [56]:
ranarr.min()

1

In [57]:
# 최댓값 위치 찾기

ranarr.argmax()

4

In [59]:
# 최솟값 위치 찾기

ranarr.argmin()

6

In [61]:
print(ranarr[4])
print(ranarr[6])

48
1


In [63]:
# 데이터 타입
ranarr.dtype

dtype('int32')

# (8)  3강-3. Numpy 인덱싱과 선택
- 전체 배열에 대한 조건부 선택과 인덱싱, 선택 브로드캐스팅
- 기본적으로 인덱싱을 통해 1차원 배열이나 2차원 배열에서 단일 요소를 가져올 수 있음
- 선택을 통해 1차원 배열이나 2차원 요소 슬라이싱 가능

In [64]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
# 대괄호 인덱싱

arr[8]

8

In [66]:
arr[1:5]

array([1, 2, 3, 4])

In [68]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [69]:
arr[:5]

array([0, 1, 2, 3, 4])

In [70]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

`브로드 캐스팅`

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [75]:
new_arr = arr / 2
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# 배열의 슬라이스
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [81]:
slice_of_arr[:] = 99

In [82]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

- 원래 배열을 호출하면 처음 5개 요소가 모두 변경됨
- `슬라이스를 기반으로 재할당에 브로드캐스팅을 수행하면 기존 배열에 변화`

In [83]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
arr_copy = arr.copy() 

In [85]:
arr_copy[:] = 10000

In [86]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [87]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### Indexing on 2d array

In [88]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [89]:
arr_2d.shape

(3, 3)

In [90]:
arr_2d[1]

array([20, 25, 30])

In [91]:
arr_2d[1][1]

25

In [92]:
arr_2d[1,1]

25

In [93]:
# 해당 배열에서 45 가져오기

arr_2d[2,2]

45

In [95]:
# 10,15와 25,30 을 부분 집합으로 하는 배열 가져오기

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

#### 조건부 선택(조건부 불리언 연산)

In [97]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [99]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [100]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [101]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [102]:
arr[arr==2]

array([2])

In [103]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

# (9)  3강-4. Numpy 연산

In [104]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
# 간단한 산술연산
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [106]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [107]:
(arr + 2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [108]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [109]:
1/arr

C:\Users\PC\anaconda3\envs\vmconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [110]:
arr/arr

C:\Users\PC\anaconda3\envs\vmconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

`universal fuctnion`

In [112]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [113]:
np.log(arr)

C:\Users\PC\anaconda3\envs\vmconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [114]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [115]:
arr.sum()

45

In [116]:
arr.mean()

4.5

In [117]:
arr.max()

9

In [118]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [119]:
arr_2d.shape

(3, 4)

In [120]:
arr_2d.sum()

78

In [123]:
# 행에 걸쳐 연산이 수행 됨 (각 열의 총합이 됨)
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [124]:
# 열에 걸쳐 연산이 수행 됨 (각 행의 총합이 됨)
arr_2d.sum(axis=1)

array([10, 26, 42])

# (10) 3강-5. Numpy 연습